# .bashrc

# Source global definitions.
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Set vi key mappings in shell.
set -o vi

# Make sure tab-completion works.
bind '"\C-i":complete'

# Put commands executed from history on command line before executing.
shopt -s histverify

# User environment variables.
if echo $PATH | grep -vq /usr/local/bin ; then
    export PATH=/usr/local/bin:$PATH
fi
if echo $PATH | grep -vq $HOME/bin ; then
    export PATH=$HOME/bin:$PATH
fi
if echo $MANPATH | grep -vq $HOME/share/man ; then
    export MANPATH=$HOME/share/man:$MANPATH
fi

# Functions.
function dr() {
    # Run docker image with pwd mounted to /src.
    docker run --rm -it -v $(pwd):/src ${1} /bin/bash
}

function ft() {
    # Find files by type.
    find . -type ${1:f}
}

function fx() {
    # Find files by extension passed as input.
    find . -iregex ".*\.${1:txt}$"
}

function fxg() {
    # Find files by extension and grep.
    find . -iregex ".*\.${1:txt}$" -exec grep -H --color "${2:-.}" {} \;
}

# Aliases.
alias drmc='docker rm $(docker ps --all --quiet --filter status=exited)'
alias drmi='docker images -aq -f 'dangling=true' | xargs docker rmi'
alias drc10='docker run --rm -it -v $(pwd):/src clang10:local'
alias drg10='docker run --rm -it -v $(pwd):/src gcc10:local'
alias dru20='docker run --rm -it -v $(pwd):/src ubuntu20:local'
alias drvim='docker run --rm -it -v $(pwd):/src vim:local'
alias gt='go test ./...'
alias gtv='go test -v ./...'
alias la='ls -laG'
alias ll='ls -lG'

# Set prompt text to blue and prompt to black.
PS1='\[\e[1;34m\]\u@\h \W\[\e[0m\]\$ '

# Golang.
if [ -d $HOME/go ] ; then
    export GOPATH=$HOME/go
    if echo $PATH | grep -vq $GOPATH ; then
        export PATH=$PATH:$GOPATH/bin
    fi
fi

# direnv: environment switcher
# https://github.com/direnv/direnv
eval "$(direnv hook bash)"

# pyenv: python switcher
# https://github.com/pyenv/pyenv
eval "$(pyenv init -)"

